Brightspace/d2l-hypermedia-constants

CODEOWNERS, d2l-hm-constants-behavior.html
This is more inline with what we're doing with other rels, where anything on subdomain.api.brightspace.com maps to HypermediaRels.subdomain.relGoesHere.
This is a breaking change, so will come with a major version bump.
Also added `CODEOWNERS` with myself in it - anybody else want me to add them? Once we've got a few people in it, would be good to add the proper branch protection to require a review from a `CODEOWNER` (although I don't have perms to enable that on this repo)
=> Move theme rels

d2l-hm-constants-behavior.html
=> Rename theme logo rel to be a bit less redundant

d2l-hm-constants-behavior.html
[This PR over here](https://github.com/Brightspace/d2l-upcoming-assessments-ui/pull/41) highlighted that these rels haven't been added yet. Soooo here they are!
=> Adding next-period and previous-period rels

d2l-hm-constants-behavior.html
Upon doing this, I've realized that rels are in capitalized namespaces, but classes are not... :|
=> Add some more classes

d2l-hm-constants-behavior.html
Should probably match the namespacing that is being used elsewhere.
=> Yeah so um

d2l-hm-constants-behavior.html
Assignments will now return a sub-entity with richtext instructions, like this:
```
{
"class": ["assignment"],
"properties": {
"name": "On Fleek",
"dueDate": "2017-09-29T15:25:00.000Z",
"draft": false
},
"entities": [{
"class": ["attachments"],
"rel": ["https://assignments.api.brightspace.com/rels/attachments"]
}, {
"class": ["richtext", "instructions"],
"properties": {
"html": "<p>Get them brows <strong>on fleek</strong>, girl!</p>",
"text": "Get them brows on fleek, girl!"
},
"rel": ["item", "https://assignments.api.brightspace.com/rels/instructions"]
}],
"links": [REDACTED],
"rel": ["https://assignments.api.brightspace.com/rels/assignment"]
}
```
And quizzes will similarly return their description as a richtext sub-entity:
```
{
"class": ["quiz"],
"properties": {
"name": "Tribute"
}, …
```
=> Add new rels and classes for the richtext concept

d2l-hm-constants-behavior.html
Our initial `grade` rel is really for a `user-grade` and was mis-named. We will shortly be adding a proper `grade` entity which will contain gradeItem information (name, description, etc) as part of [US91652](https://rally1.rallydev.com/#/157196228032d/detail/userstory/168917670620). This PR sets us up for that on the UI side, but as it represents breaking changes (logically) with regards to the existing `grade` rel it will require a major version bump on release.
=> BREAKING: grade becomes user-grade, add grade description entries

d2l-hm-constants-behavior.html
These are incorrect. This change will necessitate a major version bump.
=> Remove `high` and `low` course image classes

d2l-hm-constants-behavior.html
Adds all of the `rels` and `classes` introduced in the awards hypermedia api. Latest values are found in [this PR](https://git.dev.d2l/projects/CUST/repos/awards-service/pull-requests/700/diff#D2L.Awards/WebService/Hypermedia/AwardsSerializer.cs).
=> Add awards rels and classes

index.js
This should probably be in a `Meetings` sub-domain but all of the other `my*` rels are in the main area, including `myNotifications` which matches this pattern. So for 'consistency', and for now, placing it here.
Used here: https://github.com/Brightspace/parent-portal-ui/pull/696/files#diff-c65a063fbab6389c0d0aea3530319547R123
=> Add my-meetings rel

package.json
I guess we've been doing manual releases rather than using the version/tag thing document in the README, because this value does not match the release version. Bumping this up to bring it in line.
=> Match package to current release

index.js
This rel is slightly unfortunate in that it ends with `-usage` unlike others, but this has been in place for a few months - so can't really change it all that easily right now.
=> Add course-offering-activity class

d2l-hypermedia-constants.js
In d2l-rubric p3 conversion, I have been seeing "Could not resolve module specifier "index.js" in file "C:\source\d2l-rubric\node_modules\d2l-hypermedia-constants\d2l-hypermedia-constants.js"."
This PR is to correct the issue.
=> add ./ to index.js import and annotate behaviour

index.js
This rel identifies that the current entity represents sorts that could be applied to your collections route (the exact same as the `filters` rel, except for sorting)
=> US103199 - Add sorts rel

index.js
This link is added by the `CanonicalUserEnrolledUserLinkProvider` - been around for a while, just never made it into here.
=> Add canonical-user rel

index.js
This is already being used by the content domain (possibly other places as well), so should be included here.
=> Add preexisting completion rel

index.js
Adding 2 missing classes for assignments:
- `annotated` for annotated pdf download links
- `assignment-submission` for assignment submission entities, which was previously missing
=> Add `annotated` and `assignment-submission` classes

index.js
[US130301 ](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fuserstory%2F605256500003) on Rally.
Needed for https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/660
=> US130301 - adding constant for quiz rel under quizzes API subdomain

index.js, package.json
Adding `search-course-collection` constant from `Organization` entity to be used to get the course list in Course Publisher.
=> Add search-course-collection action

package.json
The `npm` page has really old info, I think because the repo name is incorrect.
=> Fix repo paths

.github/workflows/release.yml
Hi 👋 , I'm from team Gaudi. This PR is to fix an issue we identified with `incremental-release` where changes on maintenance branches (e.g. hotfixes on `release/2022.9.x`) are being published as "latest" and being used by the current BSI, instead of it using only the main branch.
This change moves publishing into `incremental-release`, which will tag maintenance branch releases appropriately so that they're not treated as `latest`. We recently made similar changes with `match-lms-release`, e.g. here:
https://github.com/Brightspace/consistent-evaluation/pull/1084
Note that we will also need to make these changes on any active maintenance branches, so that they use the proper pipeline.
If this repo supports squash merging, then this PR won't trigger a release - I will include `[skip …
=> Publish with incremental-release

index.js
- [US151818](https://rally1.rallydev.com/#/?detail=/userstory/698745477223&fdp=true): [FACE] Add activity details to the rubrics popout for non-ME evaluations
- [US152087](https://rally1.rallydev.com/#/?detail=/userstory/699342559785&fdp=true): [AA][ME][FACE] Adding activity details to the rubrics popout—Aggregate 
- Brightspace/lms#35784
- Brightspace/consistent-evaluation#1567
Helps determine whether or not to display the new activity details component in popout rubrics
`explicitEvaluations` may not be the ideal location for this class
=> Add advanced-assessment class

index.js
This fixes all instances of `level-of-achievment`. The [backend](https://github.com/Brightspace/lms/blob/master/le/lo/D2L.LE.LO/Extensibility/Hypermedia/Demonstrations/Entities/LoaLevel/Serializers/LoaLevelSerializer.cs#L99-L100) sends both `level-of-achievment` and `level-of-achievement` so this is fine. Will remove workaround in backend once all other instances of the spelling error are gone.
Outcomes change: https://github.com/Brightspace/d2l-outcomes/pull/697
LMS change: https://github.com/Brightspace/lms/pull/39097
=> Fix spelling mistake

index.js
https://desire2learn.atlassian.net/browse/NIM-3358
Required by: https://github.com/BrightspaceHypermediaComponents/activities/pull/4937
=> NIM-3358 - Add AA rels and classes

index.js
JIRA Link: [PHNX-2108](https://desire2learn.atlassian.net/browse/PHNX-2108)
This PR adds a Quizzes.viewSubmissionResults Rel (`https://quizzes.api.brightspace.com/rels/view-quiz-submission-results`). This is added for explicitly differentiating the `submissionLink` in the `actor-quiz-attempt-activity-provider` (vs. just looking for the `relative-uri` sub-entity), see related PRs below.
- UCE: https://github.com/Brightspace/unified-content-experience/pull/1561
- LMS: https://github.com/Brightspace/lms/pull/58192
[PHNX-2108]: https://desire2learn.atlassian.net/browse/PHNX-2108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PHNX-2108: Get data for row-content for quizzes

index.js
[EP-1344: Activity Display > 20.25.1 > description section is displaying at the top of the page for lti 1.1](https://desire2learn.atlassian.net/browse/EP-1344)
- This PR adds a description const the Content to enable LTI descriptions.
1.  https://github.com/Brightspace/smart-curriculum/pull/2229 *Remove old description view when AD
2. https://github.com/Brightspace/unified-content-experience/pull/1749 *Add new description
_screenshot of old_
_screenshot of new_
=> EP-1344: Add Description Const to Content

index.js
https://desire2learn.atlassian.net/browse/NIM-4113
=> NIM-4113 - add constants needed for super quick eval

index.js
Stop hardcoding Rels / Actions constants in `parent-portal-ui`. Refer to `d2l-hypermedia-constants`. If does not exist, add it.
Related PR:
https://github.com/Brightspace/parent-portal-ui/pull/1810
=> VOY-1: Add Rels used by `parent-portal-ui`
