d2l-hm-constants-behavior.html
Now with new sub-domain goodness!
=> Add all-my-children rel to the hm constants behavior

d2l-hm-constants-behavior.html
For stories https://rally1.rallydev.com/#/89963236876d/detail/userstory/122669728092 and https://rally1.rallydev.com/#/89963236876d/detail/userstory/125014012176
=> US87149 Adding first name relationship

d2l-hm-constants-behavior.html
This behavior was created after the bulk of work was done on My Courses, so it wasn't initially used. Buuut, it was used in one place (which, okay, I removed), but figured might as well use it in more places. These are all the rels/classes/actions that I found that are being used.
Didn't remove/change anything, just added new stuff.
=> Add rels/classes/actions found in My Courses

d2l-hm-constants-behavior.html
[Rally Story](https://rally1.rallydev.com/#/89963236876d/detail/userstory/143870052700)
[Stash PR](https://git.dev.d2l/projects/CORE/repos/le/pull-requests/8105/overview)
=> Add activities action select-custom-date-range

d2l-hm-constants-behavior.html
https://git.dev.d2l/projects/CORE/repos/le/pull-requests/8360/overview
=> Add my-activity-usage rel

d2l-hm-constants-behavior.html
https://git.dev.d2l/projects/CORE/repos/lp/pull-requests/6850/overview
=> Add HM constants for upcoming notifications API

d2l-hm-constants-behavior.html
https://git.dev.d2l/projects/CORE/repos/lp/pull-requests/6992/overview
=> Add link to future digest pref service

d2l-hm-constants-behavior.html
For [this story](https://rally1.rallydev.com/#/157196228032/detail/userstory/163823704268)
=> US91179 Add activities rel for user activity usage

d2l-hm-constants-behavior.html
will be used for https://rally1.rallydev.com/#/157196228032/detail/userstory/182501935108
=> add course-offering

README.md
=> Update readme URL

d2l-hm-constants-behavior.html
Related:
https://git.dev.d2l/projects/CORE/repos/le/pull-requests/10010/overview
https://github.com/Brightspace/d2l-activity-details-ui/pull/46
=> add in an activityGrade rel

d2l-hm-constants-behavior.html
Forgot this as part of the awards changes.
=> Add issue-date class

index.js, package.json
These are values that exist on the HM API that were missed and not included here. Unfortunately there's no easy way to _enforce_ adding values here other than on an as-required basis :(
=> US100491 add missing values

index.js
=> US100491 Add forgotten last name rel

index.js
This is now being sent by https://git.dev.d2l/projects/CORE/repos/le/pull-requests/12287/overview
=> Added update rel.

index.js
`sequence` is referenced by `organization`
Not sure if this should be under `Content:` or `Organization:`
=> Added Hypermedia Rel for sequence

index.js
Used here: https://github.com/Brightspace/parent-portal-ui/pull/696/files#diff-c65a063fbab6389c0d0aea3530319547R165
=> Add meeting-management-tool rel

index.js
Used here: https://github.com/Brightspace/parent-portal-ui/pull/696/files#diff-c65a063fbab6389c0d0aea3530319547R163
=> Add meetings.bookable class

index.js
Activities can have evaluation, the rel is from http://search.dev.d2l/source/xref/Lms/lp/framework/tools/D2L.LP.Tools.Extensibility/Hypermedia/Activities/Serializers/Default/EvaluationSerializer.cs#33
=> Adding rel for evaluation on activities

index.js
Added new rels based on https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/1920/diff#le/dropbox/D2L.LE.Dropbox.Extensibility/HM/Activities/Plugins/AssignmentActivityUsageEvaluationStatusProvider.cs
=> adding new assesment rels

index.js
Just some classes that we're using the notifications pipeline that I noticed were missing.
=> Add missing classes

index.js
Just more stuff that I've found that was missing from here - better late than never.
=> Add more missing values

index.js
...I keep thinking I've found all the missing ones in the work that I'm currently doing, but I keep finding more 😬
I've now finished what I was doing, though - so this should be the last one! 🤞
=> More missing things!

index.js
=> Add missing description class

index.js
=> rubrics associations

index.js
https://rally1.rallydev.com/#/29180338367d/detail/userstory/391701573856
=> Vwong/us116676 - add deferredRemoveAlignment action

package.json
Need to do this manually due to:
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
```
I don't have permission to push to Master directly.
=> New version: 6.34.0

.travis.yml
Not sure if this will fix things or not.
=> fix NPM token

index.js
adding a rel for feedback attachments. Attachments that live on evaluation feedback.
=> add feedback attachments rel

index.js
Activities API is updating to use actors for groups support instead of users, add this rel constant.
=> Add the actor-activity-usage rel

index.js
adding a new rel for user pronouns that will be returned from enrolled-users hypermedia API
=> Adding user-pronouns rel

index.js
new link from enrolled users api to the user profile card settings api
=> Add rel settings/userProfileCard

index.js
[US130671](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fuserstory%2F605996000365) on Rally
=> Adding activity-usage-view-application rel

index.js, package.json
[US131181](https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fuserstory%2F607688803785)
=> US131181 - adding classes for CE quiz attempt info

index.js
[US128606](https://rally1.rallydev.com/#/?detail=/userstory/600466036461&fdp=true)
=> US128606 - Adding quiz overall summary constants

index.js
Used in [d2l-rubric](https://github.com/Brightspace/d2l-rubric/blob/9e31eb114305751e6f94705c59a7e8060a4e5527/src/entities/rubric-criterion-entity.js#L10-L12)
=> Add activity alignments hierarchical rel

index.js, package.json
[US133034](https://rally1.rallydev.com/#/?detail=/userstory/612598992809&fdp=true): FACE > Add "Advanced Evaluation" section to the right panel
=> Added learner candidates activity relationship

index.js, package.json
https://rally1.rallydev.com/#/57732444928ud/custom/373260458992?detail=%2Fuserstory%2F620689133337
=> Added missing links for rubric criterion

index.js, package.json
[US135014 - [CE][Quizzing][UI] Add multiple choice question type to CE](https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fuserstory%2F621832591733)
=> US135014 - Consistent Evaluation - Quizzing - Adding new question rels

index.js
Rally: https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fuserstory%2F605447998471
Adding Long Answer constant for Classes.question to distinguish Written Response / Long Answer question type.
=> Adding long answer constant to Classes.question

index.js, package.json
For [US134275  - [CE][Quizzing][UI] Add Graded-By instructor name when question score is not auto-graded](https://rally1.rallydev.com/#/42960320374d/backlog?detail=%2Fuserstory%2F618663103555)
=> US134275 - Consistent Evaluation - Quizzing - new constants for autograded VS gradedby

index.js
PR for constants: https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/891
Rally: https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fuserstory%2F628624126081
=> Adding constants for published and unevaluated

index.js
For Rally: https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fuserstory%2F608939929551
=> Adding Rel Constant for viewing event log

package.json
Syncing version in package.json to release version.
=> Updating package.json from 6.62.0 to 6.63.0 to match release

index.js, package.json
[US139345](https://rally1.rallydev.com/#/?detail=/userstory/637756162473&fdp=true): Add new relationships to hypermedia constants
=> Added new relationships for advanced assessment

index.js
Copied from siren-sdk
https://github.com/BrightspaceHypermediaComponents/siren-sdk/blob/master/src/hypermedia-constants.js#L118
=> Add content type Rels

index.js
https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fdefect%2F643064105705
=> DE49311 - CE - Quizzing - Adding grading constants for SA

index.js
https://rally1.rallydev.com/#/?detail=/userstory/644280021699&fdp=true
*** Do not merge until the following are merged:
https://github.com/Brightspace/d2l-rubric/pull/2138
https://github.com/Brightspace/consistent-evaluation/pull/1193
=> US142118 remove no longer used RichtextEditorConfig

index.js
https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fuserstory%2F632862914445
=> US138595 - Consistent Eval - Quizzes - Added constants for FITB question type

index.js
https://rally1.rallydev.com/#/?detail=/userstory/646702879491&fdp=true
=> Grading Screen - remove references to grace period & calculations

index.js
[US144296](https://rally1.rallydev.com/#/?detail=/userstory/660037401969&fdp=true): [CE][Quizzing][UI] Build UI component for Completion Summary Grade Statistics table
LMS PR: https://github.com/Brightspace/lms/pull/29181
Added `Classes.quizzes.quizAttempt: 'quiz-attempt'`
=> US144296 - CE Quizzing "quiz-attempt" class

index.js
https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fuserstory%2F664674688269
=> US144630 - Consistent Eval - Quizzes - added rel for question activity

index.js
Needed for displaying outcomes text in quizzing completion summary
https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fuserstory%2F660677636661
=> US14382 - Consistent Eval - Adding alignments class

index.js
[US146093](https://rally1.rallydev.com/#/?detail=/userstory/672335953979&fdp=true): [Consistent Evaluation][Quizzing][UI] Add section information to Quiz attempts left panel
=> US146093 - Section constants

index.js
[US148387](https://rally1.rallydev.com/#/?detail=/userstory/685205948377&fdp=true)
- Missing constants needed in CE
- Re-alphabetizing
=> US148387 - Adding missing constants needed in CE

index.js
[US148387](https://rally1.rallydev.com/#/?detail=/userstory/685205948377&fdp=true)
- More missing hypermedia constants used in CE
=> US148387 - Adding more missing CE constants

index.js
Reverts Brightspace/d2l-hypermedia-constants#204
=> Revert "fixing published hypermedia constant"

index.js
[US148387](https://rally1.rallydev.com/#/?detail=/userstory/685205948377&fdp=true)
=> Move 'assessments' actions to 'evaluation' for accuracy

index.js
[US147561](https://rally1.rallydev.com/#/?detail=/userstory/676697248071&fdp=true): [AA][ME][UI] Build RHP UI component for evaluator tabs
=> US147561 - Explicit evaluation constants

index.js
[US150088](https://rally1.rallydev.com/#/?detail=/userstory/692304676209&fdp=true)
=> US150088 - ready-aggregate constant

index.js
[US150854](https://rally1.rallydev.com/#/?detail=/userstory/695896079945&fdp=true): [AA][ME][UI] Aggregated tab read-only and buttons disabled until all evaluations are published
Added the publisherEntity constant to know if someone has the publisher class.
=> US150854 - Added the publisherEntity constant to know if someone has the publisher class.

index.js
Related to story [US150855](https://rally1.rallydev.com/#/?detail=/userstory/695897496681&fdp=true): [AA][ME][UI] Wording for Ready to Aggregate button, Update button, etc.
=> Added explicit-evaluation class

index.js
[US150883](https://rally1.rallydev.com/#/?detail=/userstory/696163540751&fdp=true)
=> US150883 - Add explicitEvaluationCompleted class

index.js
[US154935](https://rally1.rallydev.com/#/?detail=/userstory/707115397349&fdp=true)
=> Add rubrics associations rel

index.js
[US154579](https://rally1.rallydev.com/#/?detail=/userstory/706085888151&fdp=true): [ui] Rendering textblock activity
=> US154579 adding rels needed for this story

index.js
[US154579](https://rally1.rallydev.com/#/?detail=/userstory/706085888151&fdp=true): [ui] Rendering textblock activity
=> US154579 add textblock classes and actions

index.js
[US154837](https://rally1.rallydev.com/#/?detail=/userstory/706585799745&fdp=true): [api] Save activity collection
Add create-instance action for activity instance
=> US154837 add create-instance action

index.js
Add a rel for user initials
[US157808](https://rally1.rallydev.com/#/15545167705d/custom/21568985922?detail=%2Fuserstory%2F722493250763)
=> US157808 - Add "initials" rel

index.js
[[US155666]: [CE][AA][UI] Update buttons in Consistent Evaluation with the new ready to review requirements](https://rally1.rallydev.com/#/?detail=/userstory/717745013577&fdp=true)
- needed 2 new constants to send backend actions:
- draft-update and ready-review
=> US155666 : new constants for draft-update and ready-review

index.js
[DE56111](https://rally1.rallydev.com/#/?detail=/defect/732307839847&fdp=true): UMUC > UMUC > 20.23.10.18222 > LE - Site Performance >  Latency seen in some tools in courses with a large number of enrollments
For use in CE
related: https://github.com/Brightspace/lms/pull/44690
=> DE56111 - Add Assignments no-metrics rel

index.js
[US160689](https://rally1.rallydev.com/#/?detail=/userstory/732016675719&fdp=true): [CE][AA][UI] Fix Active Scoring rubric logic - Using AAU sub-entity vs evaluation sub-entity
For: https://github.com/Brightspace/consistent-evaluation/pull/1819
- Chose to put it in activities because I couldn't find a better place for it
=> US160689 - Add 'unsaved' class

index.js
Reverts Brightspace/d2l-hypermedia-constants#227
=> Revert "DE56111 - Add Assignments no-metrics rel"

index.js
[NIM-2737](https://desire2learn.atlassian.net/browse/NIM-2737?atlOrigin=eyJpIjoiYzYyNGU0N2RhYjNjNGI4ZDkyNmYzNzc0NTFjYzQ3N2QiLCJwIjoiaiJ9) - Added a removed class for this ticket. 
[NIM-2737]: https://desire2learn.atlassian.net/browse/NIM-2737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NIM-2737: Added a removed class

index.js
https://desire2learn.atlassian.net/browse/NIM-2754
=> NIM-2754 - Add SaveFeedbackExtra constant

index.js
[NIM-2741](https://desire2learn.atlassian.net/browse/NIM-2741)
[NIM-2741]: https://desire2learn.atlassian.net/browse/NIM-2741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NIM-2741 - Create removed evaluator class

index.js
[NIM-3226](https://desire2learn.atlassian.net/browse/NIM-3226)
[NIM-3226]: https://desire2learn.atlassian.net/browse/NIM-3226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NIM-3226 - add removed evaluator rel

index.js
Need this for an update to Parent Portal.
https://desire2learn.atlassian.net/browse/VOY-2584
=> Add folio content-list rel

index.js
LMS: https://github.com/Brightspace/lms/pull/57607/files#diff-c9ca75ee67a9efa445ccc0595c0f49b502b935058ea0c7a07b0b098ccc1eae4dR205
[HAI-461 - [UI] CE grading view - add study support feedback](https://desire2learn.atlassian.net/browse/HAI-461)
=> HAI-461 Add studySupport rel to Quizzes

index.js
[HAI-459 - [API] modify existing API in CE to expose new remediation API](https://desire2learn.atlassian.net/browse/HAI-459)
See: https://github.com/Brightspace/lms/blob/master/le/quizzing/D2L.LE.Quizzing/WebServices/Api/Hypermedia/Serializers/QuizzesStudySupportAttemptSirenSerializer.cs#L29
=> HAI-459 Add Quizzes class `study-recommendations`

index.js
https://desire2learn.atlassian.net/browse/BORG-4371
Required by: https://github.com/BrightspaceHypermediaComponents/questions/pull/523
=> BORG-4371 - Add duplicate-response class for MSA question type

index.js
https://desire2learn.atlassian.net/browse/BORG-4351
=> BORG-4351: Add constants

index.js
https://desire2learn.atlassian.net/browse/BORG-4362
=> Borg-4362: add constant - significant question

index.js
https://desire2learn.atlassian.net/browse/BORG-4353
=> Borg-4353: add constants for questions

index.js
https://desire2learn.atlassian.net/browse/NIM-3840
=> NIM-3840 - Add rubric text class

index.js
https://desire2learn.atlassian.net/browse/PHNX-2428
* https://github.com/Brightspace/consistent-evaluation/pull/2103
=> Add 'mark-thread-read' action

index.js
PR for https://desire2learn.atlassian.net/browse/HAI-1229
=> HAI-1229: Add insights API

index.js
https://desire2learn.atlassian.net/browse/BORG-4801
=> BORG-4801 Add retaken constant for quizAttemptRetaken

index.js
https://desire2learn.atlassian.net/browse/BORG-4703
=> borg-4703: add action names for reopen attempts feature

index.js
Adds the `view-as-parent` rel from https://github.com/Brightspace/lms/pull/68264.
https://desire2learn.atlassian.net/browse/VOY-3351
=> VOY-3351 Add view-as-parent rel

index.js
https://desire2learn.atlassian.net/browse/PHNX-3140
=> Add 'mark-post-read' action

index.js
https://desire2learn.atlassian.net/browse/NIM-2919
=> NIM-2919 - Add new classes for group AA

index.js
https://desire2learn.atlassian.net/browse/NIM-2919
missed one!
=> NIM-2919 - add group-candidates rel

index.js
https://desire2learn.atlassian.net/browse/NIM-3182
Examples of the classes
=> NIM-3182 - Add advanced-assessment and shared-evaluation constants
